### ISSUE TITLE
How it works tab in bottom banner invalid

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#1]
<img width="1030" alt="Screen Shot 2020-04-02 at 3 44 04 PM" src="https://user-images.githubusercontent.com/63063244/78294918-300c1b80-74f9-11ea-831b-d51f49da9a0a.png">

**Comment by Caitlinpowell** [comment]
<img width="579" alt="Screen Shot 2020-04-02 at 3 46 02 PM" src="https://user-images.githubusercontent.com/63063244/78296552-ed980e00-74fb-11ea-8dde-2f474c667ca0.png">

**Comment by mattsema** [comment]
SSL certificate failed due to switch to purchased certificate.  The link resolves correctly now.
