### ISSUE TITLE
PDF for activity cards sample needs replacement

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#10]
typo- One = On 

<img width="834" alt="Screen Shot 2020-04-03 at 9 29 05 AM" src="https://user-images.githubusercontent.com/63063244/78365837-aa867b00-758d-11ea-8b44-b4c6da508152.png">
<img width="307" alt="Screen Shot 2020-04-03 at 9 29 14 AM" src="https://user-images.githubusercontent.com/63063244/78365842-ac503e80-758d-11ea-9cb4-924aa55f395a.png">

**Comment by kneesen22** [comment]
Caitlin, do you guys want to fix this one and resend or find another card to attach that you can pass along?
