### ISSUE TITLE
Text to change in Past & Present

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#12]
The STREAMin3 curriculum pilot **is in the midst of being** fully implemented during the 2019-2020 school year with extensive data collection in over 100 participating pilot classrooms. The pilot evaluation helps to further improve the STREAMin3 model’s ability to best serve children and to guide use of the curriculum and professional development supports.

[https://streamin3.org/streamin%C2%B3-curriculum-model-2/about-streamin%C2%B3/past-and-present/(url)

Change to reflect the school closure- 

**Was fully implemented**

<img width="1155" alt="Screen Shot 2020-04-08 at 4 53 35 PM" src="https://user-images.githubusercontent.com/63063244/78832632-968daf80-79b9-11ea-81e2-77b8ae21b8ba.png">

**Comment by sarahlydic** [comment]
fixed
