### ISSUE TITLE
STRM3: Meet the Team page listing -incorrect order

### ISSUE THREAD

**Issue by mrushfinn** [castl350/Streamin3#14]
From Amanda:
Meet the Team page - incorrect order for staff listing
https://streamin3.org/streamin%c2%b3-curriculum-model-2/about-streamin%c2%b3/streamin%c2%b3-team/

Order to be listed:
2.	The coaches need to be listed first after Caitlin Powell  and for other UVA staff to be listed last. Here is the order that it needs to be:
Me, kate, ginny
Caitlin Powell, Stephanie Adams, Katherine Alvarado
Jen Fry, Shirley McCullough, Sandy Patillo-Mason, 
Chanell Paynter, Tara Powell, Autumn Shaffer
Sheri Simons,  Pat Willhelm-Bennett, Melissa Williams
Leah Chilson, Lauren Condoluci, Lily Hummer, 
Ann L’Hospital, Allison Leach, Miriam Rushfinn, 
Erin Vines

**Comment by sarahlydic** [comment]
fixed
