### ISSUE TITLE
STRM3: Professional Development - typo and 'optional superhead'

### ISSUE THREAD

**Issue by mrushfinn** [castl350/Streamin3#15]
Professional Development - change data-drive and text optional superhead
https://streamin3.org/streamin%c2%b3-curriculum-model-2/how-it-works/data-driven-professional-development/

'data-driven' not data-drive...
Our curriculum model is paired with a data-driven professional development approach that builds a teacher’s toolbox.

States 'optional superhead'
![image](https://user-images.githubusercontent.com/63241553/79151768-0b396300-7d99-11ea-86e6-0e3e5b26065e.png)

**Comment by kneesen22** [comment]
done
