### ISSUE TITLE
STRM3: subheading - change

### ISSUE THREAD

**Issue by mrushfinn** [castl350/Streamin3#17]
How it Works page
https://streamin3.org/streamin%c2%b3-curriculum-model-2/how-it-works/
Bottom section
Subheading "Curriculum Component" not correct for text below. Delete subheading.
Leave - The Skills That Matter Most

![image](https://user-images.githubusercontent.com/63241553/79160474-d385e780-7da7-11ea-97c3-8df43457894c.png)

**Comment by kneesen22** [comment]
done
