### ISSUE TITLE
STRM3: subheading change

### ISSUE THREAD

**Issue by mrushfinn** [castl350/Streamin3#18]
About STREAMin3 page - 
https://streamin3.org/streamin%c2%b3-curriculum-model-2/about-streamin%c2%b3/

Lower left corner: Delete subheading 'Quick Highlights'
Doesn't work well with content and is unnecessary. Leave Hallmarks of STREAMin3

![image](https://user-images.githubusercontent.com/63241553/79160600-10ea7500-7da8-11ea-953e-436ce7b790aa.png)

**Comment by kneesen22** [comment]
done
