### ISSUE TITLE
meet the partners "participating virginia programs" link not working 

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#2]
https://streamin3.org/streamin%C2%B3-curriculum-model-2/about-streamin%C2%B3/meet-the-partners/

Last paragraph " Participating Virginia Programs"
<img width="831" alt="Screen Shot 2020-04-02 at 4 03 35 PM" src="https://user-images.githubusercontent.com/63063244/78296444-c3465080-74fb-11ea-9c73-ba503000b80e.png">
<img width="1147" alt="Screen Shot 2020-04-02 at 4 03 41 PM" src="https://user-images.githubusercontent.com/63063244/78296446-c5101400-74fb-11ea-9476-7a577c4f32fc.png">

**Comment by kneesen22** [comment]
fixed
