### ISSUE TITLE
Meet the partners logos don't link

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#3]
hyperlinked text works in paragraphs. A hand cursor appears over the images so it looks like you should be able to click them, but you can't(for any on this page).

<img width="906" alt="Screen Shot 2020-04-02 at 4 07 08 PM" src="https://user-images.githubusercontent.com/63063244/78296660-21733380-74fc-11ea-9964-19a206914c6d.png">

**Comment by kneesen22** [comment]
linked in...
