### ISSUE TITLE
Take a Look Button not working 

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#4]
<img width="944" alt="Screen Shot 2020-04-02 at 4 24 33 PM" src="https://user-images.githubusercontent.com/63063244/78297910-9cd5e480-74fe-11ea-9caa-050fe85570f2.png">
<img width="1120" alt="Screen Shot 2020-04-02 at 4 24 43 PM" src="https://user-images.githubusercontent.com/63063244/78297917-9e9fa800-74fe-11ea-8ba1-e58956d56631.png">

**Comment by kneesen22** [comment]
linked in.
