### ISSUE TITLE
PDF linked in crosswalks needs to be updated

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#5]
<img width="767" alt="Screen Shot 2020-04-02 at 4 33 48 PM" src="https://user-images.githubusercontent.com/63063244/78298664-b710c200-7500-11ea-9806-3f2fad5b1ecc.png">
<img width="875" alt="Screen Shot 2020-04-02 at 4 33 53 PM" src="https://user-images.githubusercontent.com/63063244/78298666-b7a95880-7500-11ea-8bff-f6c638cdb3e0.png">

Blank 2nd page of PDF needs to be deleted

**Comment by kneesen22** [comment]
We can relink when you send us new version? will keep ticket open.
