### ISSUE TITLE
Foundation Blocks PDF needs updating

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#6]
<img width="1069" alt="Screen Shot 2020-04-02 at 4 44 45 PM" src="https://user-images.githubusercontent.com/63063244/78298948-62217b80-7501-11ea-812f-3c5200a332d6.png">
<img width="748" alt="Screen Shot 2020-04-02 at 4 44 53 PM" src="https://user-images.githubusercontent.com/63063244/78298964-677ec600-7501-11ea-88f6-db206c3265ea.png">

Title says" Foundation Blocks", but PDF is an outdated version that call=s these "Building Blocks" Need to replace this PDF

**Comment by kneesen22** [comment]
Great. If you can send us the PDF, we'l link the new one in?
