### ISSUE TITLE
Crosswalks section logos don't link to external sites

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#7]
<img width="1191" alt="Screen Shot 2020-04-02 at 4 49 18 PM" src="https://user-images.githubusercontent.com/63063244/78364567-a9544e80-758b-11ea-93ba-5ed9e5bd9699.png">

Not sure if they are supposed to, but there's a hand cursor when you scroll over the picture.

**Comment by kneesen22** [comment]
great catch, but nothing we can do about this now. This bloock automatically provides an optional link in that image section, so we'll have to take it out as a whole....leave for now.
