### ISSUE TITLE
Both links on The Curriculum Model "A comprehensive approach" paragraph broken

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#8]
<img width="1028" alt="Screen Shot 2020-04-03 at 9 18 04 AM" src="https://user-images.githubusercontent.com/63063244/78364799-14058a00-758c-11ea-91d9-13c07f5160e9.png">
<img width="1140" alt="Screen Shot 2020-04-03 at 9 17 55 AM" src="https://user-images.githubusercontent.com/63063244/78364801-15cf4d80-758c-11ea-9300-adb08077f109.png">

[https://streamin3.org/streamin%C2%B3-curriculum-model-2/how-it-works/curriculum-overview/(url)

**Comment by kneesen22** [comment]
fixed
