### ISSUE TITLE
Picture routing

### ISSUE THREAD

**Issue by Caitlinpowell** [castl350/Streamin3#9]
<img width="893" alt="Screen Shot 2020-04-03 at 9 25 02 AM" src="https://user-images.githubusercontent.com/63063244/78365386-069ccf80-758d-11ea-8f68-5314208e2153.png">

Pictures are clickable but bring you up to to the top of the page

**Comment by kneesen22** [comment]
pictures and buttons are now clickable and open up PDF in new window
